CREATE SCHEMA dott AUTHORIZATION postgres;

CREATE TABLE dott.customer (
	id_customer int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(255) NOT NULL,
	shipping_address varchar(4000) NULL,
	phone_number varchar(13) NULL,
	credit_rating float4 NULL,
	CONSTRAINT customer_pk PRIMARY KEY (id_customer)
);

CREATE TABLE dott.product (
	"name" varchar(500) NULL,
	category varchar(500) NULL,
	price float8 NULL,
	id_product int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at date NULL,
	CONSTRAINT product_pk PRIMARY KEY (id_product)
);

CREATE TABLE dott."order" (
	id_customer int4 NULL,
	id_order int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at date NULL,
	CONSTRAINT order_pk PRIMARY KEY (id_order)
);
ALTER TABLE dott."order" ADD CONSTRAINT customer_fk FOREIGN KEY (id_customer) REFERENCES dott.customer(id_customer);

CREATE TABLE dott.item (
	id_order int4 NULL,
	id_product int4 NULL,
	quantity float8 NULL,
	applied_price float8 NULL,
	id_item int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	CONSTRAINT item_pk PRIMARY KEY (id_item)
);

ALTER TABLE dott.item ADD CONSTRAINT order_fk FOREIGN KEY (id_order) REFERENCES dott."order"(id_order) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE dott.item ADD CONSTRAINT product_fk FOREIGN KEY (id_product) REFERENCES dott.product(id_product) ON DELETE CASCADE;